import { TProduct } from "@/types/shared";

export const CLEARANCE_SALES: TProduct[] = [
  {
    id: "1",
    name: "Open Bookshelf",
    price: 59890,
    oldPrice: 112874,
    rating: 0,
    discount: 39,
    image: "Open Bookshelf",
    type: "clearance",
  },
  {
    id: "2",
    name: "Grandpa's Couch",
    price: 30800,
    oldPrice: 38500,
    rating: 0,
    discount: 5,
    image: "Grandpa's Couch",
    type: "clearance",
  },
  {
    id: "3",
    name: "Nomadic Clay Vase",
    price: 9890,
    oldPrice: 12874,
    rating: 0,
    discount: 19,
    image: "Nomadic Clay Vase",
    type: "clearance",
  },
  {
    id: "4",
    name: "Ocean Blue Seat",
    price: 50800,
    oldPrice: 68500,
    rating: 0,
    discount: 20,
    image: "Ocean Blue Seat",
    type: "clearance",
  },
  {
    id: "5",
    name: "Raffia Pattern Table",
    price: 108253,
    oldPrice: 152874,
    rating: 0,
    discount: 39,
    image: "Raffia Pattern Table",
    type: "clearance",
  },
  {
    id: "6",
    name: "Minimal Vases",
    price: 30800,
    oldPrice: 38500,
    rating: 0,
    discount: 5,
    image: "Minimal Vases",
    type: "clearance",
  },
  {
    id: "7",
    name: "Summer Dinner Table",
    price: 39890,
    oldPrice: 42874,
    rating: 0,
    discount: 19,
    image: "Summer Dinner Table",
    type: "clearance",
  },
  {
    id: "8",
    name: "Family of Three Table",
    price: 18253,
    oldPrice: 19874,
    rating: 0,
    discount: 20,
    image: "Family of Three Table",
    type: "clearance",
  },
];

export const NORDIC_TABLES: TProduct[] = [
  {
    id: "1",
    name: "Beige-Wood Table",
    price: 38253,
    oldPrice: 52874,
    rating: 4.32,
    discount: 39,
    image: "Beige-Wood Table",
    type: "nordic",
  },
  {
    id: "2",
    name: "Summer Dinner Table",
    price: 30800,
    oldPrice: 36500,
    rating: 4.92,
    discount: 39,
    image: "Summer Dinner Table",
    type: "nordic",
  },
  {
    id: "3",
    name: "Nordic Table",
    price: 89759,
    oldPrice: 100890,
    rating: 3.62,
    discount: 39,
    image: "Nordic Table",
    type: "nordic",
  },
  {
    id: "4",
    name: "Minimal Sitting",
    price: 32253,
    oldPrice: 55000,
    rating: 4.32,
    discount: 39,
    image: "Minimal Sitting",
    type: "nordic",
  },
  {
    id: "5",
    name: "Raffia Pattern Table",
    price: 108253,
    oldPrice: 152874,
    rating: 4.92,
    discount: 39,
    image: "Raffia Pattern Table",
    type: "nordic",
  },
  {
    id: "6",
    name: "Family of Three Table",
    price: 18253,
    oldPrice: 19874,
    rating: 3.85,
    discount: 39,
    image: "Family of Three Table",
    type: "nordic",
  },
  {
    id: "7",
    name: "Simple Dinner Table",
    price: 40890,
    oldPrice: 42874,
    rating: 4.82,
    discount: 39,
    image: "Simple Dinner Table",
    type: "nordic",
  },
  {
    id: "8",
    name: "Conceptual Table Top",
    price: 79900,
    oldPrice: 89874,
    rating: 4.82,
    discount: 39,
    image: "Conceptual Table Top",
    type: "nordic",
  },
  {
    id: "9",
    name: "Nomad & Urban",
    price: 49850,
    oldPrice: 50874,
    rating: 3.35,
    discount: 39,
    image: "Nomad & Urban",
    type: "nordic",
  },
  {
    id: "10",
    name: "Grandpa's Favorite ",
    price: 30800,
    oldPrice: 36500,
    rating: 4.32,
    discount: 39,
    image: "Grandpa's Favorite ",
    type: "nordic",
  },
  {
    id: "11",
    name: "Classic Dinning",
    price: 99890,
    oldPrice: 102874,
    rating: 4.72,
    discount: 39,
    image: "Classic Dinning",
    type: "nordic",
  },
  {
    id: "12",
    name: "Marbled Table",
    price: 50800,
    oldPrice: 68500,
    rating: 3.92,
    discount: 39,
    image: "Marbled Table",
    type: "nordic",
  },
];

export const SOFAS: TProduct[] = [
  {
    id: "1",
    name: "Mint Meets Green",
    price: 29007,
    oldPrice: 32874,
    rating: 4.12,
    discount: 39,
    image: "Mint Meets Green",
    type: "sofas",
  },
  {
    id: "2",
    name: "Ocean Blue Seat",
    price: 50800,
    oldPrice: 6850,
    rating: 4.98,
    discount: 39,
    image: "Ocean Blue Seat",
    type: "sofas",
  },
  {
    id: "3",
    name: "Mint Plush Sofa",
    price: 69759,
    oldPrice: 80890,
    rating: 3.22,
    discount: 39,
    image: "Mint Plush Sofa",
    type: "sofas",
  },
  {
    id: "4",
    name: "All White Comforter",
    price: 32253,
    oldPrice: 55000,
    rating: 3.1,
    discount: 39,
    image: "All White Comforter",
    type: "sofas",
  },
  {
    id: "5",
    name: "Corduroy Seams",
    price: 68253,
    oldPrice: 82874,
    rating: 3.72,
    discount: 39,
    image: "Corduroy Seams",
    type: "sofas",
  },
  {
    id: "6",
    name: "Knitted Pattern Sofa",
    price: 38253,
    oldPrice: 42874,
    rating: 3.99,
    discount: 39,
    image: "Knitted Pattern Sofa",
    type: "sofas",
  },
  {
    id: "7",
    name: "Pink Plush Sofa",
    price: 40890,
    oldPrice: 42874,
    rating: 4.52,
    discount: 39,
    image: "Pink Plush Sofa",
    type: "sofas",
  },
  {
    id: "8",
    name: "Conceptual Box Seat",
    price: 89670,
    oldPrice: 89874,
    rating: 5.0,
    discount: 39,
    image: "Conceptual Box Seat",
    type: "sofas",
  },
  {
    id: "9",
    name: "Sunny Two Friends",
    price: 49850,
    oldPrice: 50874,
    rating: 4.93,
    discount: 39,
    image: "Sunny Two Friends",
    type: "sofas",
  },
  {
    id: "10",
    name: "Beach’s Side View ",
    price: 30000,
    oldPrice: 76500,
    rating: 4.92,
    discount: 39,
    image: "Beach’s Side View ",
    type: "sofas",
  },
  {
    id: "11",
    name: "Classic Counter Stools",
    price: 199890,
    oldPrice: 200874,
    rating: 3.32,
    discount: 39,
    image: "Classic Counter Stools",
    type: "sofas",
  },
  {
    id: "12",
    name: "Cinema Couches",
    price: 70800,
    oldPrice: 88500,
    rating: 3.0,
    discount: 39,
    image: "Cinema Couches",
    type: "sofas",
  },
];

export const VASES: TProduct[] = [
  {
    id: "1",
    name: "Beige-Flower Placer",
    price: 12665,
    oldPrice: 12874,
    rating: 4.47,
    discount: 39,
    image: "Beige-Flower Placer",
    type: "sofas",
  },
  {
    id: "2",
    name: "Minimal Vases",
    price: 30800,
    oldPrice: 36500,
    rating: 4.38,
    discount: 39,
    image: "Minimal Vases",
    type: "sofas",
  },
  {
    id: "3",
    name: "Primitive & Modern",
    price: 9759,
    oldPrice: 10190,
    rating: 3.62,
    discount: 39,
    image: "Primitive & Modern",
    type: "sofas",
  },
  {
    id: "4",
    name: "Minimal Sitting",
    price: 5500,
    oldPrice: 5650,
    rating: 4.9,
    discount: 39,
    image: "Minimal Sitting",
    type: "sofas",
  },
  {
    id: "5",
    name: "Very Delicate",
    price: 8450,
    oldPrice: 12874,
    rating: 2.42,
    discount: 39,
    image: "Very Delicate",
    type: "sofas",
  },
  {
    id: "6",
    name: "Opposite Shades",
    price: 18253,
    oldPrice: 19874,
    rating: 4.19,
    discount: 39,
    image: "Opposite Shades",
    type: "sofas",
  },
  {
    id: "7",
    name: "White on White",
    price: 10490,
    oldPrice: 12874,
    rating: 4.82,
    discount: 39,
    image: "White on White",
    type: "sofas",
  },
  {
    id: "8",
    name: "Shelf Vases",
    price: 9900,
    oldPrice: 10000,
    rating: 3.0,
    discount: 39,
    image: "Shelf Vases",
    type: "sofas",
  },
  {
    id: "9",
    name: "Turquoise Blues",
    price: 14850,
    oldPrice: 30874,
    rating: 3.05,
    discount: 39,
    image: "Turquoise Blues",
    type: "sofas",
  },
  {
    id: "10",
    name: "Sand and Branch",
    price: 8400,
    oldPrice: 16500,
    rating: 4.72,
    discount: 39,
    image: "Sand and Branch",
    type: "sofas",
  },
  {
    id: "11",
    name: "Planters",
    price: 5890,
    oldPrice: 10874,
    rating: 2.42,
    discount: 39,
    image: "Planters",
    type: "sofas",
  },
  {
    id: "12",
    name: "Marbled Cup Vases",
    price: 9830,
    oldPrice: 18500,
    rating: 4.52,
    discount: 39,
    image: "Marbled Cup Vases",
    type: "sofas",
  },
];

export const DATA = {
  clearance: CLEARANCE_SALES,
  nordic: NORDIC_TABLES,
  sofas: SOFAS,
  vases: VASES,
};
