import { TProduct } from "@/types/shared";

export const CLEARANCE_SALES: TProduct[] = [
  {
    id: "1",
    name: "Open Bookshelf",
    price: 59890,
    oldPrice: 112874,
    rating: 0,
    discount: 39,
    image: "Open Bookshelf",
    type: "clearance",
  },
  {
    id: "2",
    name: "Grandpa's Couch",
    price: 30800,
    oldPrice: 38500,
    rating: 0,
    discount: 5,
    image: "Grandpa's Couch",
    type: "clearance",
  },
  {
    id: "3",
    name: "Nomadic Clay Vase",
    price: 9890,
    oldPrice: 12874,
    rating: 0,
    discount: 19,
    image: "Nomadic Clay Vase",
    type: "clearance",
  },
  {
    id: "4",
    name: "Ocean Blue Seat",
    price: 50800,
    oldPrice: 68500,
    rating: 0,
    discount: 20,
    image: "Ocean Blue Seat",
    type: "clearance",
  },
  {
    id: "5",
    name: "Raffia Pattern Table",
    price: 108253,
    oldPrice: 152874,
    rating: 0,
    discount: 39,
    image: "Raffia Pattern Table",
    type: "clearance",
  },
  {
    id: "6",
    name: "Minimal Vases",
    price: 30800,
    oldPrice: 38500,
    rating: 0,
    discount: 5,
    image: "Minimal Vases",
    type: "clearance",
  },
  {
    id: "7",
    name: "Summer Dinner Table",
    price: 39890,
    oldPrice: 42874,
    rating: 0,
    discount: 19,
    image: "Summer Dinner Table",
    type: "clearance",
  },
  {
    id: "8",
    name: "Family of Three Table",
    price: 18253,
    oldPrice: 19874,
    rating: 0,
    discount: 20,
    image: "Family of Three Table",
    type: "clearance",
  },
];

export const NORDIC_TABLES: TProduct[] = [
  {
    id: "1",
    name: "Beige-Wood Table",
    price: 38253,
    oldPrice: 52874,
    rating: 4.32,
    discount: 39,
    image: "Beige-Wood Table",
    type: "nordic",
  },
  {
    id: "2",
    name: "Summer Dinner Table",
    price: 30800,
    oldPrice: 36500,
    rating: 4.92,
    discount: 39,
    image: "Summer Dinner Table",
    type: "nordic",
  },
  {
    id: "3",
    name: "Nordic Table",
    price: 89759,
    oldPrice: 100890,
    rating: 3.62,
    discount: 39,
    image: "Nordic Table",
    type: "nordic",
  },
  {
    id: "4",
    name: "Minimal Sitting",
    price: 32253,
    oldPrice: 55000,
    rating: 4.32,
    discount: 39,
    image: "Minimal Sitting",
    type: "nordic",
  },
  {
    id: "5",
    name: "Raffia Pattern Table",
    price: 108253,
    oldPrice: 152874,
    rating: 4.92,
    discount: 39,
    image: "Raffia Pattern Table",
    type: "nordic",
  },
  {
    id: "6",
    name: "Family of Three Table",
    price: 18253,
    oldPrice: 19874,
    rating: 3.85,
    discount: 39,
    image: "Family of Three Table",
    type: "nordic",
  },
  {
    id: "7",
    name: "Simple Dinner Table",
    price: 40890,
    oldPrice: 42874,
    rating: 4.82,
    discount: 39,
    image: "Simple Dinner Table",
    type: "nordic",
  },
  {
    id: "8",
    name: "Conceptual Table Top",
    price: 79900,
    oldPrice: 89874,
    rating: 4.82,
    discount: 39,
    image: "Conceptual Table Top",
    type: "nordic",
  },
  {
    id: "9",
    name: "Nomad & Urban",
    price: 49850,
    oldPrice: 50874,
    rating: 3.35,
    discount: 39,
    image: "Nomad & Urban",
    type: "nordic",
  },
  {
    id: "10",
    name: "Grandpa's Favorite ",
    price: 30800,
    oldPrice: 36500,
    rating: 4.32,
    discount: 39,
    image: "Grandpa's Favorite ",
    type: "nordic",
  },
  {
    id: "11",
    name: "Classic Dinning",
    price: 99890,
    oldPrice: 102874,
    rating: 4.72,
    discount: 39,
    image: "Classic Dinning",
    type: "nordic",
  },
  {
    id: "12",
    name: "Marbled Table",
    price: 50800,
    oldPrice: 68500,
    rating: 3.92,
    discount: 39,
    image: "Marbled Table",
    type: "nordic",
  },
];

export const DATA = {
  clearance: CLEARANCE_SALES,
  nordic: NORDIC_TABLES,
};
